manifest:
  self:
    path: .
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: google
      url-base: https://github.com/google
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true
    - name: pigweed
      remote: google
      revision: main 
      path: modules/lib/pigweed