manifest:
  self:
    path: .
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: pigweed-project
      url-base: https://github.com/pigweed-project
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true
      path: third_party/pigweed/environment/packages/zephyr
    - name: pigweed
      remote: pigweed-project
      revision: main 
      path: third_party/pigweed
      import: false